# TiR Tweaks by Hana @gaycoderprincess
# enjoy, nya~ :3

[main]
no_cd = true			# Disable the CD check on startup
no_videos = false		# Disable all videos, unstable but can fix some crashes on wine/proton, only use if you know what you're doing!
skip_intro = false		# Skip intros and splash screens
fix_scaling = true		# Fix stretched view
fix_hud = true			# Fix stretched hud, WIP, breaks menus
letterbox_movies = true		# Makes movies and splash screens 4:3 letterboxed instead of stretched
windowed = false		# Runs the game in windowed mode, make sure to change res_x and res_y first!
borderless_windowed = false	# Runs the game in a borderless window, works independently of the built-in windowed option
multisampling = 0		# Anti-aliasing quality, 0 to disable

[extras]
res_x = 0			# Horizontal screen resolution, use 0 to autodetect
res_y = 0			# Vertical screen resolution, use 0 to autodetect
aspect_ratio = 0		# Screen aspect ratio, represented as the product e.g. 1.77777 for 16:9, use 0 to autodetect
shadow_res = 1024		# 128x by default
reflection_res = 1024		# 256x by default
high_draw_distance = true	# Increases the draw distance for vehicles and map objects
full_splash = false		# Enable 2 unused extra splash screens on startup
no_needle_fix = false		# Disables the speedometer needle scaling fix
show_debug_info = false		# Enables a debug display for some of the mod's features